import { createHash } from "node:crypto";

import { PGlite } from "@electric-sql/pglite";
import fc from "fast-check";
import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";

import type { DurableReproductionRecord } from "@/application/ports/production";
import { createCase } from "@/domain/case";
import { createJob } from "@/domain/job";
import { ContentAddressedArtifactStore } from "@/infrastructure/artifacts/content-addressed-store";
import { applyPostgresMigrations } from "@/infrastructure/postgres/migrations";
import { PostgresDurableReproductionRepository } from "@/infrastructure/postgres/repositories";

import { MemoryPrivateBlobClient } from "./helpers/memory-private-blob-client";
import { pgliteMigrationClient } from "./helpers/pglite-migration-client";
import { pglitePostgresDatabase } from "./helpers/pglite-postgres-database";

vi.setConfig({ hookTimeout: 30_000, testTimeout: 120_000 });

describe("content-addressed artifact properties", () => {
  let database: PGlite;
  let store: ContentAddressedArtifactStore;
  let record: DurableReproductionRecord;
  let sequence = 0;

  beforeAll(async () => {
    database = new PGlite();
    await applyPostgresMigrations(pgliteMigrationClient(database));
    const postgres = pglitePostgresDatabase(database);
    const at = new Date("2026-07-19T20:00:00.000Z");
    record = {
      callerId: "caller_artifact_property",
      caseId: "case_artifact_property",
      commandHash: "a".repeat(64),
      createdAt: at.toISOString(),
      idempotencyKey: "artifact_property",
      jobId: "job_artifact_property",
      snapshot: {
        case: createCase("case_artifact_property", at),
        job: createJob("job_artifact_property", "case_artifact_property", at),
        result: null,
        sampleId: "cli-spaces",
        schemaVersion: "2.0",
      },
      tenantId: "tenant_artifact_property",
      updatedAt: at.toISOString(),
      version: 1,
    };
    await database.query("INSERT INTO tenants (id) VALUES ($1)", [record.tenantId]);
    await new PostgresDurableReproductionRepository(postgres).reserve(record);
    store = new ContentAddressedArtifactStore(
      postgres,
      new MemoryPrivateBlobClient(),
      { now: () => at },
    );
  });

  afterAll(async () => {
    await database.close();
  });

  it("round-trips and deletes every generated byte sequence by canonical digest", async () => {
    await fc.assert(
      fc.asyncProperty(
        fc.uint8Array({ minLength: 0, maxLength: 256 }),
        async (generated) => {
          sequence += 1;
          const prefix = new Uint8Array(new Uint32Array([sequence]).buffer);
          const bytes = new Uint8Array(prefix.byteLength + generated.byteLength);
          bytes.set(prefix);
          bytes.set(generated, prefix.byteLength);
          const sha256 = createHash("sha256").update(bytes).digest("hex");
          const descriptor = {
            artifactId: `artifact_property_${sequence}`,
            byteCount: bytes.byteLength,
            caseId: record.caseId,
            createdAt: "2026-07-19T20:00:00.000Z",
            kind: "run-output" as const,
            objectKey: `tenants/${record.tenantId}/cases/${record.caseId}/run-output/${sha256}`,
            retentionUntil: "2026-08-19T20:00:00.000Z",
            sha256,
            tenantId: record.tenantId,
          };

          await expect(store.put({ bytes, descriptor })).resolves.toEqual(descriptor);
          const read = await store.read(
            {
              callerId: record.callerId,
              principalId: record.callerId,
              tenantId: record.tenantId,
            },
            descriptor.artifactId,
          );
          expect(read?.bytes).toEqual(bytes);
          await expect(
            store.delete(
              {
                callerId: record.callerId,
                principalId: record.callerId,
                tenantId: record.tenantId,
              },
              descriptor.artifactId,
            ),
          ).resolves.toBe(true);
        },
      ),
      { numRuns: 250 },
    );
  });
});
